import { Poppins } from 'next/font/google'
import "./globals.css";

const poppins = Poppins({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})
export const metadata = {
  title: "Blacksmith",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
      <div className='absolute top-0 left-0 z-40'>
      </div>
    </html>
  );
}
